Ensure sub-query use for Job instances.
spring-cloud/spring-cloud-dataflow pull request #5563
Opened 2023-11-23 10:26 UTC by corneil

Fix find by name query ordering.
 Fix find by name not found query.
 Improve test case readability.
 #5484

2023-11-27 02:04 UTC, onobc requested changes
Thanks for the PR @corneil . I have a few comments/change requests to take a look at please. 

Also, is there a test that exhibits the bug this is fixing? If not, can we make one or is this a performance related issue?

2023-11-27 13:28 UTC, cppwfs commented on spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
> +			.andDo(print())
They are good for diagnostic, but once we have diagnosed the issue, we should remove them.

2023-11-27 13:29 UTC, cppwfs commented on spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
> +			.andDo(print())
We can remove the print here and below.

2023-11-27 18:10 UTC, onobc commented on spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskJobService.java
> +	public Page<JobInstanceExecutions> listTaskJobInstancesForJobName(Pageable pageable, String jobName) throws NoSuchJobException {
Understood. Thanks for fixing it.

2023-11-27 18:11 UTC, onobc commented on spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
> +import static org.hamcrest.Matchers.*;
Missed this wildcard.

2023-11-27 18:11 UTC, onobc commented on spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
> +		mockMvc.perform(get("/jobs/instances/1").accept(MediaType.APPLICATION_JSON))
Discussed offline.

2023-11-27 18:14 UTC, onobc approved these changes
@corneil LGTM - thanks for the updates. There are still a couple of wildcard imports. Once these are adjusted consider this PR approved. I am approving now but please update the imports.

2023-11-27 21:18 UTC, onobc commented on spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java
>  		List<JobInstanceExecutions> taskJobInstancesForJobName = total > 0
@corneil please answer this one.

2023-11-28 08:46 UTC, corneil commented on spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/repository/JdbcAggregateJobQueryDao.java
>  		List<JobInstanceExecutions> taskJobInstancesForJobName = total > 0
The ternary operator isn't needed and refactored.

2023-11-28 08:46 UTC, corneil commented on spring-cloud-dataflow-server-core/src/test/java/org/springframework/cloud/dataflow/server/controller/JobInstanceControllerTests.java
> +			.andDo(print())
done

2023-11-28 09:27 UTC, merged