Bump PostgreSQL Driver version to 42.7.2
spring-cloud/spring-cloud-dataflow pull request #5728
Opened 2024-03-07 10:17 UTC by corneil

[CVE-2024-1597](https://avd.aquasec.com/nvd/2024/cve-2024-1597/)

2024-03-07 14:32 UTC, onobc commented on spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
> +		<spring-framework.version>5.3.32</spring-framework.version>
Please split the SF and P updates into separate commits.

2024-03-07 14:37 UTC, onobc commented on spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
> +		<spring-framework.version>5.3.32</spring-framework.version>
I see you have the commit message specifying this but it would be simple enough to just split into 2 commits and keep in this single PR is fine.

2024-03-07 14:38 UTC, onobc requested changes
Thanks @corneil - a couple of minor comments.

2024-03-08 10:03 UTC, corneil commented on spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
> +			<dependency>
It doesn't handle this properly whgen spring-framework.version property is set.

2024-03-08 12:34 UTC, cppwfs commented on spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
> +			<dependency>
Just curious, is it that its still picking the old version?

2024-03-08 15:09 UTC, onobc commented on spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
> +			<dependency>
Let me take a peek.

2024-03-09 20:24 UTC, onobc commented on spring-cloud-dataflow-build/spring-cloud-dataflow-build-dependencies/pom.xml
> +			<dependency>
I removed this and verified only version resolved is `5.3.32`.

### Steps to prove
Remove the questionable block and cd project root
```
./mvnw clean install
./mvnw dependency:tree -Dincludes='org.springframework:spring-core' | grep -E 'org.springframework:spring-core' | grep '5.3.31'
```
No results reported
```
./mvnw dependency:tree -Dincludes='org.springframework:spring-core' | grep -E 'org.springframework:spring-core' | grep '5.3.32'
```
Many results reported

2024-03-09 20:24 UTC, onobc commented
Closing via https://github.com/spring-cloud/spring-cloud-dataflow/commit/5e42287b89f0550c070dbc0a1c6075b58c4078e1

2024-03-09 20:24 UTC, closed without merging