Added TaskExecutionThinController and TaskExecutionThinResource.
spring-cloud/spring-cloud-dataflow pull request #5772
Opened 2024-04-10 12:37 UTC by corneil

2024-04-15 12:38 UTC, cppwfs requested changes
LGTM.  Just my nagging nitipicks :-)

2024-04-16 16:22 UTC, onobc approved these changes
LGTM - once @cppwfs comments are addressed. Thanks @corneil

2024-04-25 16:29 UTC, corneil commented on spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
> +			.andDo(print())
All the other tests have `print()`

2024-04-25 16:30 UTC, corneil commented on spring-cloud-dataflow-rest-client/src/main/java/org/springframework/cloud/dataflow/rest/client/TaskTemplate.java
> +		Assert.isTrue(resources.getLink(THIN_EXECUTIONS_RELATION).isPresent(), "Executions relation is required");
Rewritten for a list and a more specific message.

2024-04-25 17:26 UTC, cppwfs commented on spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
> +			.andDo(print())
True.   But we can remove it from the others unless we are doing diagnostics.    Else it fills the logs.   Its an annoying nitpick :-)

2024-04-26 17:57 UTC, cppwfs commented
Rebased Squashed Merged.   Thanks @corneil for the PR!

2024-04-26 17:57 UTC, closed without merging