the document plugin needs to use the current spring javadoc location
spring-cloud/spring-cloud-dataflow pull request #5831
Opened 2024-05-30 16:05 UTC by cppwfs

It was set to use a configurable spring version that was not set in the main-3.   When ever possible we want to use the BOM or current when determining versions.

2024-05-31 13:06 UTC, corneil requested changes
`spring-boot-dependencies` has a property named `spring-framework.version`

2024-05-31 15:11 UTC, cppwfs commented
@corneil I don't think that will work.   That is for overriding the dependency in the bom.

2024-06-04 22:13 UTC, onobc commented on spring-cloud-dataflow-build/pom.xml
> +		<spring-javadoc.version>6.1.3</spring-javadoc.version>
I think `javadoc-spring.version` might be clearer, plus if we end up needing to add another javadoc version property, the prefix keeps them "close" together. Wdyt?

2024-06-05 15:10 UTC, onobc approved these changes
LGTM - thanks @cppwfs

2024-06-06 08:36 UTC, corneil approved these changes
Let's fly.

2024-06-06 11:41 UTC, cppwfs commented
Squashed Merged

2024-06-06 11:41 UTC, closed without merging