Add support for binary/octet-stream.
spring-cloud/spring-cloud-dataflow pull request #5892
Opened 2024-08-07 13:10 UTC by corneil

Quay.io responds with binary/octet-stream when reading imageBlob.

application/octet-stream is identical to binary/octet-stream.

Fixes #5885

2024-08-20 14:27 UTC, onobc requested changes
Thanks @corneil. A couple of minor comments/suggestions, but other than that LGTM.

2024-08-22 14:06 UTC, corneil commented on spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerImageRestTemplateFactory.java
> +		mediaTypeList.add(MediaType.parseMediaType("binary/octet-stream")); // quay.io responds with binary/octet-stream instead of application/octet-stream
That can only be added with integration test using a quay.io container. We don't have existing integration tests for any of the registries.

2024-08-22 14:14 UTC, onobc commented on spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerImageRestTemplateFactory.java
> +		mediaTypeList.add(MediaType.parseMediaType("binary/octet-stream")); // quay.io responds with binary/octet-stream instead of application/octet-stream
In that case a manual test will suffice. But let's be sure we do the manual test.

2024-08-22 19:39 UTC, onobc commented on spring-cloud-dataflow-container-registry/src/main/java/org/springframework/cloud/dataflow/container/registry/ContainerImageRestTemplateFactory.java
> +		mediaTypeList.add(MediaType.parseMediaType("binary/octet-stream")); // quay.io responds with binary/octet-stream instead of application/octet-stream
@corneil if you can confirm this I will approve and merge this. Thanks.

2025-04-30 15:52 UTC, cppwfs commented
Thank you for the contribution.    

Closing this PR in preparation for archiving this project.

2025-04-30 15:52 UTC, closed without merging