Merge from main-3
spring-cloud/spring-cloud-dataflow pull request #5955
Opened 2024-09-27 13:33 UTC by corneil

- [X] Resolved compile issues, test and integration-tests.
- [ ] JUnit 5, Hamcrest -> AssertJ
- [ ] Spring Boot 3.x best practice.

**NOTE**: _Security Integration test fails since PR wasn't merged._

2024-09-30 22:10 UTC, cppwfs requested changes
@corneil Thanks for all the hard work here!   Most of the comments are nitpicks.

2024-10-01 08:44 UTC, corneil commented on .github/workflows/build-snapshot-controller.yml
> +                "ref": "main-3",
Maybe we should merge spring-cloud-deployer main-3 to main first.

2024-10-01 09:06 UTC, corneil commented on build-containers.sh
> +./mvnw install -s .settings.xml -DskipTests -T 1C -am -pl :spring-cloud-dataflow-server,:spring-cloud-skipper-server,:spring-cloud-dataflow-composed-task-runner,:spring-cloud-dataflow-tasklauncher-si
This is for building all containers locally.

2024-10-01 09:12 UTC, corneil commented on spring-cloud-common-security-config/pom.xml
> +		<relativePath>../spring-cloud-dataflow-build</relativePath>
This change was made on main-3

2024-10-01 09:16 UTC, corneil commented on spring-cloud-dataflow-build/pom.xml
> +		<maven-failsafe-plugin.version>3.0.0</maven-failsafe-plugin.version>
We aren't actually using failsafe anywhere anymore.

2024-10-01 09:38 UTC, corneil commented on spring-cloud-dataflow-build/pom.xml
> +						<loaderImplementation>CLASSIC</loaderImplementation>
Came in from main-3

2024-10-01 09:41 UTC, corneil commented on spring-cloud-common-security-config/spring-cloud-common-security-config-web/src/test/java/org/springframework/cloud/common/security/support/ExternalOauth2ResourceAuthoritiesMapperTests.java
> +	@Before
I decided to leave common security as it was in main-3 in the hope that the security changes will be easier to apply.

2024-10-01 09:43 UTC, corneil commented on spring-cloud-dataflow-build/pom.xml
> +		<maven-failsafe-plugin.version>3.0.0</maven-failsafe-plugin.version>
Bumping to 3.5.0

2024-10-01 09:44 UTC, corneil commented on spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/BaseDocumentation.java
> +											 RestDocumentationContextProvider restDocumentationContextProvider) throws Exception {
Done

2024-10-01 09:50 UTC, corneil commented on spring-cloud-dataflow-classic-docs/src/test/java/org/springframework/cloud/dataflow/server/rest/documentation/TaskExecutionsDocumentation.java
> -										fieldWithPath("schemaTarget").description("The schema target of the task state data"),
Yes

2024-10-01 09:50 UTC, corneil commented on spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker-junit5/pom.xml
> +		</dependency>
No the whole module is a dependency included as test scope when used.

2024-10-01 09:52 UTC, corneil commented on spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/main/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/DefaultDockerCompose.java
> +		if (log.isDebugEnabled()) {
The parameters passed to the log statement perform expensive operations

2024-10-01 10:06 UTC, ilayaperumalg commented on .github/workflows/build-snapshot-controller.yml
> +                "ref": "main-3",
same here: should this be `main`?

2024-10-01 10:09 UTC, ilayaperumalg commented on .github/workflows/ci-carvel.yml
> +      - main-3
why do we need `main-3` still?

2024-10-01 10:57 UTC, cppwfs commented on .github/workflows/build-snapshot-controller.yml
> +                "ref": "main-3",
Agreed!

2024-10-01 11:01 UTC, cppwfs commented on spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker-junit5/pom.xml
> +		</dependency>
Gotcha.  Could we then remove the `<scope>test</scope> from the `spring-boot-starter-test` for consistency?

2024-10-01 11:04 UTC, cppwfs commented on build-containers.sh
> +./mvnw install -s .settings.xml -DskipTests -T 1C -am -pl :spring-cloud-dataflow-server,:spring-cloud-skipper-server,:spring-cloud-dataflow-composed-task-runner,:spring-cloud-dataflow-tasklauncher-si
Gotcha.   Just making sure we were consistent.

2024-10-01 11:28 UTC, corneil commented on spring-cloud-dataflow-classic-docs/pom.xml
> +<!--							<parallel>methods</parallel>-->
Done

2024-10-01 12:49 UTC, corneil commented on spring-cloud-dataflow-autoconfigure/src/test/java/org/springframework/cloud/dataflow/autoconfigure/local/AbstractSchedulerPerPlatformTest.java
> +import static org.mockito.Mockito.mock;
fixing

2024-10-01 12:52 UTC, corneil commented on .github/workflows/ci-carvel.yml
> +      - main-3
updating

2024-10-01 15:43 UTC, cppwfs approved these changes

2024-10-01 15:47 UTC, corneil commented on spring-cloud-common-security-config/spring-cloud-common-security-config-web/src/main/java/org/springframework/cloud/common/security/OAuthSecurityConfiguration.java
> +// SCDF 3.0 Migration - Need to re add this later with a different class or bean.
done

2024-10-01 15:47 UTC, corneil commented on spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker-junit5/pom.xml
> +		</dependency>
fixed

2024-10-01 15:47 UTC, corneil commented on spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/test/java/org/springframework/cloud/dataflow/common/test/docker/compose/connection/PortsTests.java
> -		// exception.expect(IllegalArgumentException.class);
done

2024-10-01 15:48 UTC, corneil commented on spring-cloud-dataflow-common/spring-cloud-dataflow-common-test-docker/src/test/java/org/springframework/cloud/dataflow/common/test/docker/compose/execution/DockerComposeTests.java
> +import static org.assertj.core.api.Assertions.*;
fixed

2024-10-02 06:51 UTC, merged