Update Task Thin Executions list function for parity with 2.11.x
spring-cloud/spring-cloud-dataflow pull request #6063
Opened 2024-11-12 08:25 UTC by corneil

Updated task thin executions link handing and added extra test for parity with 2.11.x

See #6062

2024-11-12 22:16 UTC, cppwfs requested changes
Looks good just a couple of nitpicks

Since you are bringing this class up to date can you remove the following since they are not being used:
* the AboutResource import 
* actualDataFlowServerCoreVersion
* aboutLink

Thanks!

2024-11-13 07:15 UTC, corneil commented on spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/TaskTemplateTests.java
> +		validateExecutionLinkPresent("3.0.0");
Until the next release we will be needing those again for the versions we support.

2024-11-13 07:16 UTC, corneil commented on spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/TaskTemplateTests.java
> +		validateExecutionLinkPresent("3.0.0");
At the moment we don't have old versions we support with links missing

2024-11-13 16:17 UTC, cppwfs commented on spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/TaskTemplateTests.java
> +		validateExecutionLinkPresent("3.0.0");
Can you add a TODO to let the future coders know that this needs to be updated.

2024-11-14 14:18 UTC, corneil commented on spring-cloud-dataflow-rest-client/src/test/java/org/springframework/cloud/dataflow/rest/client/TaskTemplateTests.java
> +		validateExecutionLinkPresent("3.0.0");
Added

2024-11-14 21:18 UTC, cppwfs commented
Squashed, Rebased, Merged
@corneil Thanks for the contribution!!!!

2024-11-14 21:18 UTC, closed without merging